
spring:
  application:
    name: wordwaves
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

jwt:
  access-signer-key: ${ACCESS_SIGNER_KEY}
  refresh-signer-key: ${REFRESH_SIGNER_KEY}

app:
  email-client:
    brevo-url: https://api.brevo.com
    brevo-apikey: ${BREVO_APIKEY}
    sender:
      email: ${BREVO_SENDER_EMAIL}
      name: ${SENDER_NAME:WordWaves Support}


logging:
  file:
    name: logs/wordwaves.log # Đường dẫn và tên file log
  level:
    root: INFO




