
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

jwt:
  access-signer-key: ${ACCESS_SIGNER_KEY}
  refresh-signer-key: ${REFRESH_SIGNER_KEY}

app:
  email-client:
    brevo-apikey: ${BREVO_API_KEY}
    sender:
      email: ${BREVO_SENDER_EMAIL}






