server:
  servlet:
    context-path: /wordwaves
    encoding:
      charset: UTF-8
  port: 8080


spring:
  servlet:
    multipart:
      enabled: true
      max-request-size: 3MB
      max-file-size: 3MB
  application:
    name: wordwaves
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://avnadmin:AVNS_NaOkIhMfoLS45jVy0F4@wordwaves-wordwaves.f.aivencloud.com:21917/defaultdb?ssl-mode=REQUIRED
    username: avnadmin
    password: AVNS_NaOkIhMfoLS45jVy0F4
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


jwt:
  access-signer-key: "6FvxQMx9pcbEFqKFFP4XH748Kg//XkcCtf68+/P7ZRvIXnba3dG7POT/cUCAWV5Q"
  refresh-signer-key: "CAqDB1w3mJFJEb3ifzhGVJou64rhlft96l8FSS+i+0XGHSKb+OMxXbzOeHoLxaFL"
  access-token-duration-in-seconds: 3600 # 1h  (in seconds)
  refresh-token-duration-in-seconds: 604800 # 7 days (in seconds)

app:
  email-client:
    brevo-url: https://api.brevo.com
    brevo-apikey: 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
    sender:
      email: kaitoukido0204@gmail.com
      name: WordWaves Support
  dictionary-client:
    url: https://api.dictionaryapi.dev/api/v2/entries/en
  pexels-client:
    url: https://api.pexels.com/v1/search
  firebase:
    bucket-name: wordwaves-40814.appspot.com
