server:
  servlet:
    context-path: /wordwaves
    encoding:
      charset: UTF-8
  port: 8080
  compression:
    enabled: true

spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    cache: false
  servlet:
    multipart:
      enabled: true
      max-request-size: 3MB
      max-file-size: 3MB
  application:
    name: wordwaves
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://avnadmin:AVNS_NaOkIhMfoLS45jVy0F4@wordwaves-wordwaves.f.aivencloud.com:21917/defaultdb?ssl-mode=REQUIRED&serverTimezone=Asia/Ho_Chi_Minh
    username: avnadmin
    password: AVNS_NaOkIhMfoLS45jVy0F4
  jpa:
    hibernate:
      naming:
        physical-strategy: com.server.wordwaves.config.PascalCaseNamingStrategy
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: "233350138347-bmdnbcmrurg2vsbtfv1m1m1ug5ls7tnp.apps.googleusercontent.com"
            client-secret: "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"
          facebook:
            client-id: "1462073664414959"
            client-secret: "e3bab52757bac528b4cb35977c57acbd"

springdoc:
  swagger-ui:
    path: /api-documentation
    operations-sorter: method
    disable-swagger-default-url: true

openapi:
  service:
    api-docs: api-service
    server:
      local: http://localhost:8080/wordwaves
      dev: https://backend-production-c2cb.up.railway.app/wordwaves
    title: API Service Documentation
    version: 1.0.0


jwt:
  access-signer-key: "6FvxQMx9pcbEFqKFFP4XH748Kg//XkcCtf68+/P7ZRvIXnba3dG7POT/cUCAWV5Q"
  refresh-signer-key: "CAqDB1w3mJFJEb3ifzhGVJou64rhlft96l8FSS+i+0XGHSKb+OMxXbzOeHoLxaFL"
  access-token-duration-in-seconds: 7200 # 2h (in seconds)
  refresh-token-duration-in-seconds: 604800 # 7 days (in seconds)

app:
  email-client:
    brevo-url: https://api.brevo.com
    brevo-apikey: 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
    sender:
      email: kaitoukido0204@gmail.com
      name: WordWaves Support
  dictionary-client:
    url: https://api.dictionaryapi.dev/api/v2/entries/en
  pexels-client:
    url: https://api.pexels.com/v1/search
    apikey: FQfOWjWjZ3hi9i1Y3KT1yngoYRYnwO7FoivYa9JmDU06u8a7OUOXkEU7
  translate-client:
    url: https://api-b2b.backenster.com/b1/api/v3/translate
    apikey: a_gv6X8wZ8aSfHRn4bUop7mHW0ekmLhyYIal7XStpn9eVfgkwrSvvFxJ0BL6v0KvUlKTHY0MS4rABs600v
  firebase:
    bucket-name: wordwaves-40814.appspot.com

client:
  url: https://localhost:3001
  reset-password-path: reset-password
  verify-email-path:  verify-email
