server:
  servlet:
    context-path: /wordwaves
    encoding:
      charset: UTF-8
  port: 8080

spring:
  application:
    name: wordwaves
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  access-signer-key: ${ACCESS_SIGNER_KEY}
  refresh-signer-key: ${REFRESH_SIGNER_KEY}
  access-token-duration-in-seconds: 600 # 10 minutes (in seconds)
  refresh-token-duration-in-seconds: 604800 # 7 days (in seconds)

app:
  email-client:
    brevo-url: https://api.brevo.com
    brevo-apikey: ${BREVO_APIKEY}
    sender:
      email: ${BREVO_SENDER_EMAIL}
      name: ${SENDER_NAME:WordWaves Support}


