
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

jwt:
  access-signer-key: ${ACCESS_SIGNER_KEY}
  refresh-signer-key: ${REFRESH_SIGNER_KEY}
  access-token-duration-in-seconds: 36000 # 10 h  (in seconds)
  refresh-token-duration-in-seconds: 604800 # 7 days (in seconds)

app:
  email-client:
    brevo-apikey: ${BREVO_API_KEY}
    sender:
      email: ${BREVO_SENDER_EMAIL}






