name: WordWaves Backend Pipeline

on:
  push:
    branches:
      - main
    paths:
      - src/main/java/com/server/wordwaves/**
      - Dockerfile
  pull_request:
    branches:
      - main
    paths:
      - src/main/java/com/server/wordwaves/**
      - Dockerfile

jobs:
  build:
    runs-on: self-hosted
    name: Build and Deploy
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Build with Maven
        run: ./mvnw clean package -DskipTests

      - name: Build Docker image
        run: docker build -t quan0204/wordwaves:latest .

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push Docker image to Docker Hub
        run: docker push quan0204/wordwaves:latest

      - name: Deploy to Render
        run: |
          curl -X POST "https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys" \
          -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
          -H "Accept: application/json" \
          -H "Content-Type: application/json" \
          -d '{
                "serviceId": "${{ secrets.RENDER_SERVICE_ID }}",
                "envVars": [
                  {"key": "DATABASE_URL", "value": "${{ secrets.DATABASE_URL }}"},
                  {"key": "DATABASE_USERNAME", "value": "${{ secrets.DATABASE_USERNAME }}"},
                  {"key": "DATABASE_PASSWORD", "value": "${{ secrets.DATABASE_PASSWORD }}"},
                  {"key": "JWT_SIGNER_KEY", "value": "${{ secrets.JWT_SIGNER_KEY }}"},
                  {"key": "BREVO_APIKEY", "value": "${{ secrets.BREVO_APIKEY }}"},
                  {"key": "BREVO_SENDER_EMAIL", "value": "${{ secrets.BREVO_SENDER_EMAIL }}"}
                ]
              }'
